use_frameworks!

target 'MyPodTest_Example' do
  pod 'MyPodTest', :path => '../'

  target 'MyPodTest_Tests' do
    inherit! :search_paths

    
  end
end

# Manually making pod compiler version be swift 3.2
post_install do |installer|
    installer.pods_project.targets.each do |target|
        #        if target.name == 'NVActivityIndicatorView'
        print "Changing #{target.name} swift version to 3.2\n"
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
            #            end
        end
    end
end
